"""Initial schema

Revision ID: 06a1bc2df475
Revises: aa1c86db7067
Create Date: 2025-04-18 22:05:55.350866

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06a1bc2df475'
down_revision = 'aa1c86db7067'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('note',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['contact_id'], ['contact.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=False),
    sa.Column('order_date', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['contact_id'], ['contact.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pop',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=False),
    sa.Column('material', sa.String(length=120), nullable=True),
    sa.Column('sent_date', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['contact_id'], ['contact.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=False),
    sa.Column('task', sa.String(length=255), nullable=True),
    sa.Column('due_date', sa.String(length=120), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['contact_id'], ['contact.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('interaction_log')
    op.drop_table('follow_up_task')
    op.drop_table('pop_log')
    op.drop_table('rep_note')
    op.drop_table('order_log')
    with op.batch_alter_table('contact', schema=None) as batch_op:
        batch_op.alter_column('phone',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=120),
               existing_nullable=True)
        batch_op.alter_column('rep',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=120),
               existing_nullable=True)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rep_notes', sa.Text(), nullable=True))
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.String(length=100),
               nullable=False)
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=100),
               nullable=False)
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('password',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=120),
               nullable=True)
        batch_op.alter_column('username',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=80),
               nullable=True)
        batch_op.drop_column('rep_notes')

    with op.batch_alter_table('contact', schema=None) as batch_op:
        batch_op.alter_column('rep',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('phone',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)

    op.create_table('order_log',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('contact_id', sa.INTEGER(), nullable=True),
    sa.Column('order_date', sa.DATE(), nullable=True),
    sa.ForeignKeyConstraint(['contact_id'], ['contact.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rep_note',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('rep_name', sa.VARCHAR(length=100), nullable=True),
    sa.Column('note', sa.TEXT(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rep_name')
    )
    op.create_table('pop_log',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('contact_id', sa.INTEGER(), nullable=True),
    sa.Column('material', sa.VARCHAR(length=100), nullable=True),
    sa.Column('sent_date', sa.DATE(), nullable=True),
    sa.ForeignKeyConstraint(['contact_id'], ['contact.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('follow_up_task',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('contact_id', sa.INTEGER(), nullable=True),
    sa.Column('task', sa.VARCHAR(length=250), nullable=True),
    sa.Column('due_date', sa.DATE(), nullable=True),
    sa.Column('completed', sa.BOOLEAN(), nullable=True),
    sa.ForeignKeyConstraint(['contact_id'], ['contact.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('interaction_log',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('contact_id', sa.INTEGER(), nullable=True),
    sa.Column('note', sa.TEXT(), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['contact_id'], ['contact.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('task')
    op.drop_table('pop')
    op.drop_table('order')
    op.drop_table('note')
    # ### end Alembic commands ###
